# Generated by Django 3.1.2 on 2020-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201115_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardnumber',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='card',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
