# Generated by Django 3.1.2 on 2020-11-21 14:09

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201121_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cardnumber',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='card',
            name='password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
